name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: go-cache-paths
        name: Set up Go Cache Paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_STATE
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_STATE

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Download go dependencies
        run: go mod download

      - name: Run make all
        run: make -j4 all

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/label_linux_amd64
            bin/label_darwin_amd64
            bin/label_darwin_arm64
            bin/label_windows_amd64.exe
