name: Build and upload artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO_BUILD:
      GO_MOD:

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup Golang with cache
        id: golang-with-cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod

      - name: Download go dependencies
        run: go mod download

      - name: Run make all
        run: make -j4 all

      - name: Compress binaries
        run: zip -r bin.zip bin

      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v4
        with:
          failOnError: false
          name: bin.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin.zip
          path: bin.zip
