name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go Cache Paths
        run: |
          echo "go_build=$(go env GOCACHE)" >> "$GITHUB_ENV"
          echo "go_mod=$(go env GOMODCACHE)" >> "$GITHUB_ENV"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.go_build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.go_mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Download go dependencies
        run: go mod download

      - name: Run make all
        run: make -j4 all

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/label_linux_amd64
            bin/label_darwin_amd64
            bin/label_darwin_arm64
            bin/label_windows_amd64.exe
