name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Run make all
        run: make all

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/linux/amd64/label
            bin/darwin/amd64/label
            bin/darwin/arm64/label
            bin/windows/amd64/label.exe
