name: Release latest artifact

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Release latest artifact
    runs-on: ubuntu-latest
    env:
      GO_BUILD:
      GO_MOD:

    steps:
      - name: Download latest release
        uses: actions/download-artifact@v2
        with:
          name: bin.zip
          path: bin.zip

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: bin.zip
